services:
  surveillance:
    container_name: surveillance-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./:/app
      - /storages/cameras:/files
      - /var/run/docker.sock:/var/run/docker.sock

#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: portainer
#    environment:
#      - TZ=Europe/Moscow
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#    ports:
#      - "9000:9000"
#      - "9443:9443"
#    restart: unless-stopped
#
#volumes:
#  portainer_data: